name: Build

on: 
  workflow_dispatch:
  push:
    branches:
    - master

env: 
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Download Dalamud
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
    - name: Build
      run: |
        dotnet restore -r win XIVCombo.sln
        dotnet build --configuration Release
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: PluginRepoZip
        path: XIVComboPlugin\bin\Release\XIVComboExpandedest
        if-no-files-found: error
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: lushc/MyDalamudPlugins
        token: ${{ secrets.PAT }}
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: PluginRepoZip
        path: plugins/XIVComboExpandedest
    - name: Add, Commit, and Push
      uses: EndBug/add-and-commit@v7
      with:
        add: --all
        author_name: GitHub Action
        author_email: github-actions[bot]@users.noreply.github.com
        message: Update XIVComboExpandedest
